on:
  push: 
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Jupyter Notebooks
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: | 
          pip install jupyter
          ipython kernel install --name=python3 --user
          pip install jupytext
      - name: Build notebooks
        run: |
          rm -rf notebooks/*
          jupytext --to ipynb --execute scripts/*.py
          mv scripts/*.ipynb notebooks/
      - name: Push changes
        uses: actions-go/push@v1
        with:
          author-name: GitHub Bot
          commit-message: 'chore(build): Build Jupyter Notebooks'