jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Jupyter Notebooks
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: pip install jupyter
      - run: pip install jupytext
      - run: rm -rf notebooks/*
      - run: jupytext --to ipynb scripts/*.py
      - run: mv scripts/*.ipynb notebooks/